using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DemonTidesAP.Helpers;

public static class IslandLockingHelper
{
    public static Dictionary<string, string> IDstoNames = new()
    {
        { "Narrative_Ruins_0_Tutorial", "Shipwreck Reef" },
        { "Level_Ruins_1_RadioTowers", "Radio Towers FM" },
        { "Level_Ruins_2_WarehouseIsland", "Lokitana Smuggler's Den" },
        { "Level_Ruins_3_HighwaySkies", "Lofty Highways" },
        { "Level_Ruins_4_Outpost", "Stacked Outpost" },
        { "Level_Ruins_5_SunkenNeighborhood", "Sunken Neighborhood" },
        { "Level_Ruins_6_ChumNest", "Industrial Nest" },
        { "Level_Ruins_7_GrassyPillars", "Split Islands" },
        { "Level_Ruins_8_TradePost", "Trading Outpost" },
        { "Level_Ruins_9_GearserkerArena", "Gearserker Junction" },
        { "Narrative_Ruins_1_MerchantShips", "Merchant's Fleet" },
        { "Level_Ruins_10_Runa", "Runa's Village" },
        { "Narrative_Ruins_2_CrowsNest", "Crow's Nest" },
        { "Level_Ruins_11_Windmills", "Vindra's Mills" },
        { "Narrative_Ruins_3_VillageRuins", "Stiltsville Ruins" },
        { "Level_Ruins_12_Jester1", "Jester's Minery" },
        { "Narrative_Ruins_4_RagnarFlashback1", "Wrecked Fleet" },
        { "Level_Ruins_13_Jester2", "Jester's Juicery" },
        { "Narrative_Ruins_5_MaskShip", "Traveling Mask Shop" },
        { "Narrative_Ruins_6_CrowsNestHostile", "Hostile Crow's Nest" },
        { "Level_Ruins_14_Jester3", "Jester's Leviathan" },
        { "Narrative_Ruins_7_Campsite", "Campsite" },
        { "Micro_Ruins_1_InvisibleTower", "Dissolving Tower" },
        { "Micro_Ruins_2_GravityWell", "Gravity Well" },
        { "Micro_Ruins_3_BabyRescue", "Baby Storage" },
        { "Micro_Ruins_4_Shipwreck", "Shipwreck Twins" },
        { "Level_Ruins_15_Optica", "Blessed Optica" },
        { "Micro_Ruins_5_HandAltar", "Altar of Hands" },
        { "Narrative_Frigid_0_FirstLanding", "King's Landing" },
        { "Micro_Frigid_1_IceSlide", "Slippery Slope" },
        { "Narrative_Frigid_1_RunaCannon", "Shiverbeaks Runa's Cannon" },
        { "Level_Frigid_1_Tridentarius", "Tridentarius Gearserkium" },
        { "Level_Frigid_2_Glacier1", "Frosty Bait" },
        { "Level_Frigid_4_Snowstorm", "Snowstorm Station" },
        { "Level_Frigid_3_Tundra1", "Red Forest" },
        { "Narrative_Frigid_2_MaskShip", "Shivering Mask Shop" },
        { "Level_Frigid_5_Lighthouse", "Northern Lighthouse" },
        { "Narrative_Frigid_3_KappernianSprings", "Kappernian Springs" },
        { "Level_Frigid_6_FrozenJungle", "Arctic Eden" },
        { "Micro_Frigid_2_Collapse", "Abandoned Barrack" },
        { "Level_Frigid_7_Optica", "Optica Festival" },
        { "Level_Frigid_8_RuinedVillage", "Frostown Ruins" },
        { "Level_Frigid_9_TracyIsland", "Dunkelwald" },
        { "Level_Frigid_10_Glacier2", "Lonely Glacier" },
        { "Level_Frigid_11_Tundra2Burg", "Frost Burg" },
        { "Level_Frigid_12_GhostShip", "The Crooked Crow" },
        { "Level_Frigid_13_Volcano1", "Blazing Bonanza" },
        { "Level_Frigid_14_Volcano2", "Giant's Fire" },
        { "Level_Frigid_15_Village", "Logtown" },
        { "Narrative_Frigid_4_CrowsNest", "Freezing Crow's Nest" },
        { "Narrative_Frigid_5_RagnarFlashback2", "Abandoned Home" },
        { "Micro_Frigid_3_Iceball", "Rotund Ice" },
        { "Micro_Frigid_4_LaserChallenge", "Laser Marathon" },
        { "Narrative_Frigid_6_HostileCrowsNest", "Destroyed Crow's Nest" },
        { "Micro_Frigid_5_NightTrick", "Night Sight" },
        { "Narrative_Golden_1_RunaCannon2", "Thuintir Runa's Cannon " },
        { "Narrative_Golden_2_MaskShip", "Golden Mask Shop" },
        { "Level_Golden_1_Mines", "Aurum Mine" },
        { "Level_Golden_2_BlueCaves", "Fungal Depths" },
        { "Level_Golden_3_Skullhole", "Skull Sceal" },
        { "Level_Golden_4_Whirlpool", "Uisge Whirlpool" },
        { "Level_Golden_5_SewerRuins", "Sgudal Ruins" },
        { "Level_Golden_6_ModernRuins", "Bhaile Ruins" },
        { "Level_Golden_7_FloatingRuins1", "Subway Ascension" },
        { "Level_Golden_8_FloatingRuins2", "Heavenly Aqueducts" },
        { "Level_Golden_9_BrokenMushroom", "Shroomfall" },
        { "Level_Golden_10_Cyclone", "Chronia Cyclone" },
        { "Micro_Golden_1_Boss", "Dueling Grounds" },
        { "Level_Golden_11_BirdGaol", "Avian Gaol" },
        { "Level_Golden_12_FloodedMonastery", "Flooded Manachainn" },
        { "Level_Golden_13_VerticalCaves", "Slocfall" },
        { "Level_Golden_14_CitySewer", "Drained Urbs" },
        { "Level_Golden_15_MushroomVillage", "Tartar Village" },
        { "Micro_Golden_2_GearserkerMine", "Golden Inneal" },
        { "Narrative_Golden_3_CrowsNest", "Golden Crow's Nest" },
        { "Narrative_Golden_4_CrowsNestHostile", "Crooked Crow's Nest" },
        { "Micro_Golden_3_DKChallenge", "DK's Curse" },
        { "Micro_Golden_4_Barrels", "Twisting Barrels" },
        { "Micro_Golden_5_ShipBattle", "Naval Conflict" },
        { "Narrative_Golden_5_SmugglersCave", "Thuintir Smuggler's Den" },
        { "Narrative_Golden_6_RagnarFlashback3", "Memory Cladh" },
        { "Level_Special_RagnarCastle", "Ragnar's Castle" },
        { "Level_Special_VindraSkies", "Vindra's Skies" },
        { "Micro_Frigid_6_GearserkerIce", "Frozen Gears" },
    };

    public static Dictionary<string, bool> IsLocked = new()
    {
        { "Shipwreck Reef", true},
        { "Radio Towers FM", true},
        { "Lokitana Smuggler's Den", true},
        { "Lofty Highways", true},
        { "Stacked Outpost", true},
        { "Sunken Neighborhood", true},
        { "Industrial Nest", true},
        { "Split Islands", true},
        { "Trading Outpost", true},
        { "Gearserker Junction", true},
        { "Merchant's Fleet", true},
        { "Runa's Village", true},
        { "Crow's Nest", true},
        { "Vindra's Mills", true},
        { "Stiltsville Ruins", true},
        { "Jester's Minery", true},
        { "Wrecked Fleet", true},
        { "Jester's Juicery", true},
        { "Traveling Mask Shop", true},
        { "Hostile Crow's Nest", true},
        { "Jester's Leviathan", true},
        { "Campsite", true},
        { "Dissolving Tower", true},
        { "Gravity Well", true},
        { "Baby Storage", true},
        { "Shipwreck Twins", true},
        { "Blessed Optica", true},
        { "Altar of Hands", true},
        { "King's Landing", true},
        { "Slippery Slope", true},
        { "Shiverbeaks Runa's Cannon", true},
        { "Tridentarius Gearserkium", true},
        { "Frosty Bait", true},
        { "Snowstorm Station", true},
        { "Red Forest", true},
        { "Shivering Mask Shop", true},
        { "Northern Lighthouse", true},
        { "Kappernian Springs", true},
        { "Arctic Eden", true},
        { "Abandoned Barrack", true},
        { "Optica Festival", true},
        { "Frostown Ruins", true},
        { "Dunkelwald", true},
        { "Lonely Glacier", true},
        { "Frost Burg", true},
        { "The Crooked Crow", true},
        { "Blazing Bonanza", true},
        { "Giant's Fire", true},
        { "Logtown", true},
        { "Freezing Crow's Nest", true},
        { "Abandoned Home", true},
        { "Rotund Ice", true},
        { "Laser Marathon", true},
        { "Destroyed Crow's Nest", true},
        { "Night Sight", true},
        { "Thuintir Runa's Cannon ", true},
        { "Golden Mask Shop", true},
        { "Aurum Mine", true},
        { "Fungal Depths", true},
        { "Skull Sceal", true},
        { "Uisge Whirlpool", true},
        { "Sgudal Ruins", true},
        { "Bhaile Ruins", true},
        { "Subway Ascension", true},
        { "Heavenly Aqueducts", true},
        { "Shroomfall", true},
        { "Chronia Cyclone", true},
        { "Dueling Grounds", true},
        { "Avian Gaol", true},
        { "Flooded Manachainn", true},
        { "Slocfall", true},
        { "Drained Urbs", true},
        { "Tartar Village", true},
        { "Golden Inneal", true},
        { "Golden Crow's Nest", true},
        { "Crooked Crow's Nest", true},
        { "DK's Curse", true},
        { "Twisting Barrels", true},
        { "Naval Conflict", true},
        { "Thuintir Smuggler's Den", true},
        { "Memory Cladh", true},
        { "Ragnar's Castle", true},
        { "Vindra's Skies", true},
        { "Frozen Gears", true},
    };

    public static bool IsLockedFromID(string id)
    {
        return IsLocked[IDstoNames[id]];
    }
}
